[project]
name = "lets-go-gambling"
version = "0.1.0"
description = "Telegram bot for gambling"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.15.0",
    "python-dotenv>=1.0.1",
]
