class Database:
    def __init__(self):
        pass

    def get_score(self, id: int) -> int: ...
    def set_score(self, id: int, value: int) -> None: ...
    def get_username(self, id: int) -> str: ...
    def create_user(self, id: int, username: str) -> None: ...

    def __contains__(self, id: int) -> bool: ...


DATABASE = Database()
